import type { MetricDefinition } from './types'

export const SYSTEM_METRICS: MetricDefinition[] = [
  {
    code: 'revenue',
    name: '收入',
    metricType: 'base',
    category: 'profit',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '项目在当前期间确认的收入基础事实。',
    dependencies: [],
    sortOrder: 10,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'cost',
    name: '成本',
    metricType: 'base',
    category: 'profit',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '项目在当前期间确认的成本基础事实。',
    dependencies: [],
    sortOrder: 20,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'gross_profit',
    name: '毛利',
    metricType: 'calculated',
    category: 'profit',
    expression: 'revenue - cost',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '收入扣除成本后的项目毛利。',
    dependencies: ['revenue', 'cost'],
    sortOrder: 30,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'gross_margin',
    name: '毛利率',
    metricType: 'calculated',
    category: 'profit',
    expression: 'gross_profit / revenue',
    unit: '%',
    valueType: 'percentage',
    periodAggregation: 'recompute',
    description: '按聚合后的毛利除以聚合后的收入重新计算。',
    dependencies: ['gross_profit', 'revenue'],
    sortOrder: 40,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'cash_inflow',
    name: '现金流入',
    metricType: 'base',
    category: 'cashflow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '项目在当前期间实际或预计收到的现金。',
    dependencies: [],
    sortOrder: 50,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'cash_outflow',
    name: '现金流出',
    metricType: 'base',
    category: 'cashflow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '项目在当前期间实际或预计支付的现金。',
    dependencies: [],
    sortOrder: 60,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'net_cash_flow',
    name: '净现金流',
    metricType: 'calculated',
    category: 'cashflow',
    expression: 'cash_inflow - cash_outflow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '现金流入扣除现金流出。',
    dependencies: ['cash_inflow', 'cash_outflow'],
    sortOrder: 70,
    systemManaged: true,
    origin: 'system',
  },
  {
    code: 'cumulative_cash_flow',
    name: '累计现金流',
    metricType: 'calculated',
    category: 'cashflow',
    expression: 'previous(cumulative_cash_flow) + net_cash_flow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'ending',
    description: '上期累计现金流加本期净现金流，项目合计取期末值。',
    dependencies: ['net_cash_flow'],
    sortOrder: 80,
    systemManaged: true,
    origin: 'system',
  },
]
