import type { MetricDefinition } from './types'
import { PROFIT_METRIC_NODES } from '../../config/profitMetricHierarchy'

export const SYSTEM_METRICS: MetricDefinition[] = [
  ...PROFIT_METRIC_NODES.map((metric): MetricDefinition => ({
    code: metric.code,
    name: metric.name,
    metricType: 'base',
    category: 'profit',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: metric.isLeaf
      ? `${metric.name}末级事实，由项目预测行写入。`
      : `${metric.name}汇总指标，自动汇总全部末级后代。`,
    dependencies: [],
    sortOrder: metric.sortOrder,
    systemManaged: true,
    origin: 'system',
    parentCode: metric.parentCode,
    hierarchyLevel: metric.hierarchyLevel,
    isLeaf: metric.isLeaf,
  })),
  {
    code: 'gross_profit',
    name: '毛利',
    metricType: 'calculated',
    category: 'profit',
    expression: 'revenue - cost',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '收入扣除成本后的项目毛利。',
    dependencies: ['revenue', 'cost'],
    sortOrder: 500,
    systemManaged: true,
    origin: 'system',
    hierarchyLevel: 0,
    isLeaf: true,
  },
  {
    code: 'gross_margin',
    name: '毛利率',
    metricType: 'calculated',
    category: 'profit',
    expression: 'gross_profit / revenue',
    unit: '%',
    valueType: 'percentage',
    periodAggregation: 'recompute',
    description: '按聚合后的毛利除以聚合后的收入重新计算。',
    dependencies: ['gross_profit', 'revenue'],
    sortOrder: 510,
    systemManaged: true,
    origin: 'system',
    hierarchyLevel: 0,
    isLeaf: true,
  },
  {
    code: 'cash_inflow',
    name: '现金流入',
    metricType: 'base',
    category: 'cashflow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '项目在当前期间实际或预计收到的现金。',
    dependencies: [],
    sortOrder: 600,
    systemManaged: true,
    origin: 'system',
    hierarchyLevel: 0,
    isLeaf: true,
  },
  {
    code: 'cash_outflow',
    name: '现金流出',
    metricType: 'base',
    category: 'cashflow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '项目在当前期间实际或预计支付的现金。',
    dependencies: [],
    sortOrder: 610,
    systemManaged: true,
    origin: 'system',
    hierarchyLevel: 0,
    isLeaf: true,
  },
  {
    code: 'net_cash_flow',
    name: '净现金流',
    metricType: 'calculated',
    category: 'cashflow',
    expression: 'cash_inflow - cash_outflow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'sum',
    description: '现金流入扣除现金流出。',
    dependencies: ['cash_inflow', 'cash_outflow'],
    sortOrder: 620,
    systemManaged: true,
    origin: 'system',
    hierarchyLevel: 0,
    isLeaf: true,
  },
  {
    code: 'cumulative_cash_flow',
    name: '累计现金流',
    metricType: 'calculated',
    category: 'cashflow',
    expression: 'previous(cumulative_cash_flow) + net_cash_flow',
    unit: '元',
    valueType: 'currency',
    periodAggregation: 'ending',
    description: '上期累计现金流加本期净现金流，项目合计取期末值。',
    dependencies: ['net_cash_flow'],
    sortOrder: 630,
    systemManaged: true,
    origin: 'system',
    hierarchyLevel: 0,
    isLeaf: true,
  },
]
